name: Test
on: push
jobs:
  Flake8 & Black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install flake8
      - run: flake8 main.py
      - run: pip install Black
      - run: Black main.py

  Test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install flake8
      - run: flake8 main.py

  Print CD: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'test'

  Ping UP: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install requests
      - run: python -c "import requests; exit(1) if requests.get('https://www.google.fr').status_code != 200 else exit(0)"