name: Test
on: push
jobs:
  Flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install flake8
      - run: flake8 main.py
      - run: pip install Black
      - run: Black main.py